networks:
  dev:

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:${PORT}'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - dev
