networks:
  dev:

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:${PORT}'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - CSV_PATH=${CSV_PATH}
    networks:
      - dev
    command: npm run dev
  
  test:
    container_name: ${APP_NAME}-test
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
      - CSV_PATH=${CSV_PATH}
